#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "角落里有个祭坛，应该属于某位被淡忘的神。"
printf "\n"
echo "地面上有个小饰品（trinket）。"
echo "这东西看起来应该和宗教有关。"
echo "你要把饰品放回祭坛那里吗？"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "你把饰品放在了祭坛处。"
   echo "你感觉房间中有微风轻柔地吹过。"
   touch .bless
else
   echo "你要自己留着饰品吗？"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       echo "别忘了把饰品放入物品栏！"
       touch .curse
   else
   echo "你把饰品留在原处。"
   echo "你感到一阵悲伤。"
   echo "你觉得现在得继续前行了。"
   touch .curse
   fi
fi


















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./altar
#
# 要是没看到文件名后的“*”，搞不好是因为你忘记用 ls -F 了。



