#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "In the corner is a decaying old altar of some forgotten god."
printf "\n"
echo "There is a small trinket on the ground."
echo "It looks religious in nature."
echo "Do you want to put the trinket back on the altar?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "You place the trinket upon the altar."
   echo "You feel a gentle breeze pass through the room."
   touch .bless
else
   echo "Do you want to take the trinket for yourself?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       echo "Remember to add the trinket to your inventory!"
       touch .curse
   else
   echo "You leave the trinket where it lies."
   echo "There is a great sadness here."
   echo "You feel compelled to move on."
   touch .curse
   fi
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 


