#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "You have found a potion bottle of swirling"
echo "green liquid. Do you want to drink it?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "The taste of a rustic green plant fills your mouth."
   echo "It warms and strengthens you."
   printf "\n" 
   echo "Create a variable for your health points (HP)."
   echo "You have 15 HP:"
   echo "$ export HP=15"
   printf "\n"
else
   echo "You weren't born yestermorn;"
   echo "this potion is probably poison."
   printf "\n"   
   echo "Create a variable for your health points (HP)."
   echo "You have 10 HP:"
   echo "$ export HP=10"
   printf "\n"
fi

echo "You can check your health at any time:"
printf "\n"
echo "echo \$HP"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null




















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./potion

