#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "你找到了一瓶打着旋的绿色液体。想喝喝看吗？"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "朴实的绿色植物味道涌上舌尖。"
   echo "这味道让你感到温暖不已，还让你变强了。"
   printf "\n" 
   echo "创建个存有血量值（HP）的变量。"
   echo "你现在有 15 HP："
   echo "$ export HP=15"
   printf "\n"
else
   echo "你早就不是小孩子了，你明白这药很可能有毒。"
   printf "\n"   
   echo "创建个存有血量值（HP）的变量。"
   echo "你现在有 10 HP："
   echo "$ export HP=10"
   printf "\n"
fi

echo "你随时可以这样查看血量："
printf "\n"
echo "echo \$HP"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null




















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./potion

