#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
printf "\n"
echo "你找到了一把闪闪发光的银制 **sword** （剑）！"
echo "你对它精妙的制作惊叹不已，随之回想起儿时的传说，"
echo "伟大而神秘的 Rannismir 国王持着这样一把剑，保护受亡灵围困的王国。"
printf "\n"
echo "把这件物品装入物品栏："
printf "\n"
echo "$ export I=sword,\$I"
printf "\n"
echo "别忘了这样查看物品栏："
printf "\n"
echo "echo \$I"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null

























































































































































































































































































# 唔，这样行不通啊！
#
# 读读卷轴，说不定能找到什么线索。

