#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
printf "\n"
echo "You have found a gleaming silver **sword**!"
echo "You marvel at its craftmanship, and you recall"
echo "tales from your childhood of the great"
echo "mystic king Rannismir who bore such a sword to"
echo "protect the kingdom from undead."
printf "\n"
echo "Add this item to your inventory:"
printf "\n"
echo "$ export I=sword,\$I"
printf "\n"
echo "Remember, you can check your inventory:"
printf "\n"
echo "echo \$I"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null

























































































































































































































































































# Hmm, that didn't work!
#
# Maybe the scroll can provide a clue.

