#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
if [[ -e potion ]]; then
   echo "You have summoned a potion from afar."
   echo "You drink it quickly and feel a surge of strength."
   echo "Add 5 HP to your score."
else
   echo "A page from a druid's tome of incantations lies on the ground."
   echo "It reveals to you how to summon a healing potion:"
   printf "\n"
   echo "# To find a file on your system, use the find command."
   echo '# For example, to search this room: find . -name "potion"'
   echo "# Once you've found a potion, copy it to this directory"
   echo "# and run this spell script again."
   printf "\n"
   echo "There are no potions in this room."
   echo "But try searching starting at the entrance."
   printf "\n"
   echo "Hint: use pwd to determine how many rooms (folders)"
   echo "are between you and the entrance."
   printf "\n"
fi


















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./spell

