#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#


gameover () {
    echo "你在地牢地板上看到一具冒险者的尸体（corpse）。" > corpse
    echo "尸体周围散落着这些物品：" >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

penguin_bite () {
	echo "企鹅咬着你的包，企图找到点吃的。"
	echo '但是因为啥都没找到，它朝着你的手咬了一口，造成了 1 点伤害。（HP="let HP--"）'
	echo "如果有剑的话，你大概可以避免这点伤害，还可以攻击企鹅。"
	printf "\n"
	echo "要攻击企鹅吗？"
	read RESP
	if [ $RESP = "y" -o $RESP = "Y" ]; then
	    echo "你一击杀死企鹅，这引起了房间里其它企鹅的注意。"
	    echo "它们一齐向你冲来。你全力作战。"
        let HP=HP-5
        export HP
        if [ "$HP" -le 0 ]; then
            echo "企鹅群把你的生命值打空了。"
            echo "你被企鹅群杀害了。"
            gameover
            exit 1
        else
	        echo "但一群企鹅可容忍不了什么欺压，你很快发现自己被冰封了。"
	        echo "你被封存了 128 年，只能在这等了。等你化了冻，就能继续冒险了。"
        fi
	else
        let HP=HP--
        export HP
	    echo "你的价值观很端正，没有打企鹅。"
	fi
}

echo "终于有一只企鹅意识到了你的存在。"
echo "它把头转到一边，好像在点头示意你靠近。"
printf "\n"
echo "要走近一点吗？"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "你向前一步，鸟类立刻挤到你身边，都大张着嘴。"
   echo "你有鱼吗？"
   read RESP

    if [ $RESP = "y" -o $RESP = "Y" ]; then
        if grep -Po fish <<< $I; then
            echo "你把鱼撂给企鹅，企鹅接住半空中的鱼，狼吞虎咽起来。"
            echo
            echo "别忘了把鱼从物品栏中删除。"
            echo "试试这行命令："
            echo 
            echo 'export I=`sed "s/fish//; s/,,/,/" <<< $I`'
        else
            echo "你没有鱼！"
            echo
            penguin_bite
        fi
   else
        penguin_bite
   fi
   
else
   echo "你小心地离开企鹅群。"
   echo "那只企鹅不再注意你，摇摇晃晃走开了。"
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# 额，这样行不通！
