#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
gameover () {
    echo "你在地牢地板上看到一具冒险者的尸体（corpse）。" > corpse
    echo "尸体周围散落着这些物品：" >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}
roll() {
    echo "输入数字。"
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    echo "怪物的数字是 " $MONSTER
    echo "你的数字是 " $NUM
    
    if [ -e ../../../glass/.bless ]; then
	let "NUM=NUM+2"
	echo "+2 神秘者的寒冷加成！"
    fi
    resolve
}

resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
	echo "你躲过了机器人的攻击，但也没能打中目标。"
	echo "再来一局……"
	roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
       echo "打中了！效果拔群！"
       echo "你杀死了邪恶魔法师的灵魂。"
       echo '#!/bin/sh
            if ! grep -Po emerald <<< $I &> /dev/null; then
                echo "你找到了一颗 *绿宝石* （emerald）！"
                echo "把它装入物品栏吧。"
            else
                echo "宝藏已经被取走了。"
            fi' > treasure
       chmod +x treasure
       echo '#!/bin/sh
             if ! grep -Po platinum <<< $I &> /dev/null; then
                 echo "你找到了满满一袋 *白金* （platinum）硬币！"
                 echo "把它装入物品栏吧。"
             else
                 echo "宝藏已经被取走了。"
             fi' > platinum
       chmod +x platinum
    else
	echo "你在空气中晃悠的打法造不成一点伤害。"
	echo "敌人对你造成了 5 点伤害，要从 HP 中减掉。"
	echo 'let "HP=HP-5"'
    let HP=HP-5
    if [ "$HP" -le 0 ]; then
        echo "你突然感觉生命力从体内流失，真冷啊！"
        echo "你被邪恶魔法师的幽灵杀害了。"
        echo
        echo "游戏结束！"
        gameover
        exit 1
    fi
	printf "\n"
	roll
    fi
}

echo "房间摇晃起来，一阵风把你从某个地方吹了过来。"
echo "你感觉有谁进入了房间。"
echo "你突然感到疼痛，说明你正被幽灵攻击着！"
printf "\n"

echo "如果你有剑，可以选择攻击。"
echo "否则应该逃跑。"
echo "要攻击吗？y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then
    roll
    resolve
else
    echo "你明智地转身逃跑了。"
    echo "赶快 cd 进入上层目录。"
fi
printf "\n"


















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./ghost

