#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
if [[ -e goblet-light && -e goblet-dark ]]; then
   echo "你已经统一了高脚杯先前无规则的形式。"
   echo "现在把高脚杯放入物品栏吧。"
   exit
else 
    echo "你试着握住这只隐约发光的高脚杯，但它从你手指中穿过去了。"
fi

printf "\n"
echo "遇到困难了吗？需要提示吗？y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
 echo "试试在 opensource.com 上搜索复制文件的方法吧。"
 printf "\n"
 echo "仍然不行？需要答案吗？y/n"
 read RESP

 if [ $RESP = "y" -o $RESP = "Y" ]; then
     echo "cp 命令可以将一个文件复制成另一个。"
     echo "运行一下这行命令："
     echo "$ cp goblet-light goblet-dark"
     printf "\n"
     echo "然后再运行一下这个“高脚杯”脚本，确认一下。"
 fi
fi

printf "\n"


















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./goblet

