#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
if [[ -e goblet-light && -e goblet-dark ]]; then
   echo "You have united the gobllet's ethereal forms."
   echo "Add the goblet to your inventory."
   exit
else 
    echo "You try to grasp the faintly glowing goblet,"
    echo "but it passes through your fingers."
fi

printf "\n"
echo "Are you stuck? Do you need a hint? y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
 echo "Try searching opensource.com for"
 echo "hints on how to copy files."
 printf "\n"
 echo "Still stuck? Do you need the answer? y/n"
 read RESP

 if [ $RESP = "y" -o $RESP = "Y" ]; then
     echo "The cp command copies one file to another."
     echo "Run this command:"
     echo "$ cp goblet-light goblet-dark"
     printf "\n"
     echo "And then run this goblet script again"
     echo "for confirmation."
 fi
fi

printf "\n"


















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./goblet

