#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
gameover () {
    echo "你在地牢地板上看到一具冒险者的尸体（corpse）。" > corpse
    echo "尸体周围散落着这些物品：" >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}
roll() {
    echo "输入数字。"
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`
    echo "怪物的数字是 " $MONSTER
    echo "你的数字是 " $NUM
    resolve
}

resolve() {
    if ! grep -Po 'sword' <<< $I &> /dev/null; then
        echo "你没有剑！"
        echo
        echo "你的攻击不会很有效。"
        let NUM=NUM-10
    fi
    if [[ $MONSTER -eq $NUM ]]; then
	echo "你们的攻击相抵。"
	echo "再来一局……"
	roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
       echo "打中了！效果拔群！"
       echo "你杀死了怪物。"
       echo '#!/bin/bash
             if ! grep -Po crown <<< $I &> /dev/null; then
                 echo "你找到了一顶 *王冠* （crown）！"
                 echo "把它放入物品栏吧。"
             else
                 echo "宝藏已经被取走了。"
            fi' > treasure
       chmod +x treasure
       mv monster carcass
    else
	echo "怪物坚硬的皮肉偏转了你的攻击。"
	echo "你受到 5 点伤害，要从 HP 中减掉。"
	echo 'let "HP=HP-5"'
    let HP=HP-5
    export HP
    if [ "$HP" -le 0 ]; then
        echo "你被怪物杀害了。"
        echo 
        echo "游戏结束！"
        gameover
        exit 1
    fi
	printf "\n"
	roll
    fi
}

if [ "$0" = "./carcass" ]; then
    echo "你发现了怪物脏兮兮的尸体。"
    echo 
    echo "尸体里没什么有意思的东西。"
    exit 0
fi

echo "这有一只巨大的三条腿怪物，满嘴是尖牙、尾巴带刺、还长了八条胳膊，正向你走来。"
printf "\n"
echo "如果你有剑，可以选择攻击。"
echo "否则应该逃跑。"
echo "要攻击吗？y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then
    roll
else
    echo "你明智地转身逃跑了。"
    echo "赶快 cd 进入上层目录。"
fi
printf "\n"
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# 额，这样行不通！
