#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "古代的神秘种族一度统治这片土地，他们的语言——符文，都刻在西边的墙上。"
echo "要不要试着读一下？"
read RESP
if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "你回想起 Caitlyn the Green 教给你的古文。"
   printf "\n"
   echo "这些符文描述了如何生成一扇传送门（portal），以此通过墙壁里的隐形门。"
   printf "\n"
   echo "在 Bash 中，符号链接（软链接、symlink）是另一文件或目录的 *别名* （alias），或者说是 *快捷方式* （shortcut）。"
   echo "就在这创建一扇通往附近房间的传送门："
   echo "ln -f -s `pwd`/../../../chapel/courtyard/aviary/hall portal"
   printf "\n"
else
   echo "你想还是尽早离开更好，毕竟墙上刻着的都是魔法符文啊。"
fi



























































































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./spell

