#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "Runes, the language of the ancient mystics that once ruled"
echo "this land, are inscribed upon the western wall."
echo "Do you want to read them?"
read RESP
if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "You recall the lessons of Caitlyn the Green,"
   echo "who taught you these ancient letters."
   printf "\n"
   echo "The runes are instructions on how to summon"
   echo "a portal that will allow you to walk through"
   echo "an invisible door contained in the wall."
   printf "\n"
   echo "In Bash, a symlink is an *alias* or a *shortcut*"
   echo "to another file or directory."
   echo "Create one from this room to the adjacent one:"
   echo "ln -f -s `pwd`/../../../chapel/courtyard/aviary/hall portal"
   printf "\n"
else
   echo "You decide it is probably best to leave"
   echo "magickal enscriptions as they are."
fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./spell

