#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#

gameover () {
    echo "你在地牢地板上看到一具冒险者的尸体（corpse）。" > corpse
    echo "尸体周围散落着这些物品：" >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

if [ "$0" = "./pieces" ]; then
    echo "你在雕像碎片中翻找。"
    echo
    echo "碎片中没什么有趣的东西。"
    exit 1
fi

echo "衣衫褴褛的雕像立在房间的角落里。"
echo "走近看看吗？"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "雕像活了，发出巨响："
   echo '“是谁敢侵入神的房间？！”'
   printf "\n" 
   echo "雕像打了你一拳，造成 5 点伤害。"
   echo "从 HP 变量中减去 5 ："
   echo 'let "HP=HP-5"'
   let HP=HP-5
   export HP
   if [ "$HP" -le 0 ]; then
        echo "你被雕像杀害了。"
        echo
        echo "游戏结束！"
        gameover
        exit 1
   fi
   sed -i 's/coins/diamonds/g' ./treasure
   printf "\n"
   echo "你有剑吗？"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       if grep -Po 'sword' <<< $I &> /dev/null; then
           echo "你把雕像砍成了一堆碎片（piece）！"
           mv statue pieces
       else
           printf "\n"
           echo "不，你没有！"
           echo '傻孩子，快跑啊！'
           rm treasure
           rm spell
      fi
   else
       echo "傻孩子，快跑啊！"
   fi
else
    echo "你想起那些闹鬼墓穴里，活化的石头静静等待目标的故事，于是你小心避开了雕像。"
   printf "\n"
fi













































































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./statue

