#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#

gameover () {
    echo "You see the corpse of a slain adventurer on the floor of the dungeon." > corpse
    echo "You find the following items on the corpse:  " >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

if [ "$0" = "./pieces" ]; then
    echo "You sift through the pieces of a shattered statue."
    echo
    echo "You find nothing of interest in the statue's remains."
    exit 1
fi

echo "A rugged statue stands in the corner of the room."
echo "Do you approach it?"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "The statue springs to life, rumbling:"
   echo '"WHO DARES INTRUDE UPON THE CHAMBER OF SPIRITS?"'
   printf "\n" 
   echo "It thrusts a fist at you, hitting you for 5 damage."
   echo "Deduct 5 from your HP variable:"
   echo 'let "HP=HP-5"'
   let HP=HP-5
   export HP
   if [ "$HP" -le 0 ]; then
        echo "You have been slain by the statue."
        echo
        echo "GAME OVER!"
        gameover
        exit 1
   fi
   sed -i 's/coins/diamonds/g' ./treasure
   printf "\n"
   echo "Do you have a sword?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       if grep -Po 'sword' <<< $I &> /dev/null; then
           echo "You slay the statue!"
           mv statue pieces
       else
           printf "\n"
           echo "No you don't!"
           echo 'Run!'
           rm treasure
           rm spell
      fi
   else
       echo "Run!"
   fi
else
    echo "You cautiously avoid the statue,"
    echo "recalling stories of living stone"
    echo "lying in wait, deep within haunted catacombs."
   printf "\n"
fi













































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./statue

