#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo
if ! grep -Po coins <<< $I &> /dev/null; then
    echo "You have found a stash of **coins**!"
    echo "They are old and worn with age,"
    echo "but they still gleam in the magical light"
    echo "emanating from your eyes."
    printf "\n"
    echo "Prepend this item to your inventory:"
    printf "\n"
    echo '$ export I=coins,$I'
    printf "\n"
    echo "Remember, you can check your inventory:"
    printf "\n"
    echo 'echo $I'
    printf "\n"
else
    echo "This treasure has already been taken."
fi








































































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./treasure

