#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo
if ! grep -Po coins <<< $I &> /dev/null; then
    echo "你找到了一把埋藏的 **硬币** （coin）！"
    echo "随着时间的流逝，它们已严重磨损，但在你眼睛发出的魔光下，它们仍然熠熠生辉。"
    printf "\n"
    echo "把它们追加到物品栏中："
    printf "\n"
    echo '$ export I=coins,$I'
    printf "\n"
    echo "别忘了这样查看物品栏："
    printf "\n"
    echo 'echo $I'
    printf "\n"
else
    echo "宝藏已经被取走了。"
fi








































































































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./treasure

