#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "A metal box sits upon the ground."
echo "It appears to be illuminated from within."
echo "There is a window in the box."
echo "The window is black, but there is luminescent writing."

echo "Do you want to read the writing?"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo ".--------------------------------,"
   echo "|       Welcome to POSIX         |"
   echo "|   Enter your username:         |"
   echo "'--------------------------------'"
   read RESP
   if [ $RESP = $USER ]; then
       echo '#!/bin/sh
       echo "Welcome, $USER, to your POSIX system."
       echo "You have learnt much, and now you have"
       echo "the basic knowledge you need to become"
       echo "a truly powerful wizard."
       echo "You have found magickal armour."
       echo "Add it to your inventory."
       echo touch .armour' >> armour
       chmod +x armour
       touch .bless
    fi
else
   echo "The box is full of mystery, and it's often"
   echo "best not to look too deeply into puzzles."
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./box
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

