#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "地上有个金属盒子。"
echo "盒子里面好像发着光。"
echo "盒子上有个窗口。"
echo "这窗口是黑的，上面的字却发着光。"

echo "要读读上面的字吗？"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo ".--------------------------------,"
   echo "|         欢迎使用 POSIX         |"
   echo "|         请输入用户名：         |"
   echo "'--------------------------------'"
   read RESP
   if [ $RESP = $USER ]; then
       echo '#!/bin/sh
       echo "$USER ，欢迎您使用 POSIX 系统。"
       echo "您已学到了很多知识，已经有能力成为真正强力的。"
       echo "您发现了一套魔法护甲（armour）。"
       echo "请将它装入物品栏。"
       echo touch .armour' >> armour
       chmod +x armour
       touch .bless
    fi
else
   echo "这个盒子满是谜团，还是不要深入这些谜了。"
fi



















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./box
#
# 要是没看到文件名后的“*”，搞不好是因为你忘记用 ls -F 了。

