#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
if [ -e drum ]; then
   echo "War drums pound in the distance,"
   echo "giving Nyarlathotep strength."
   printf "\n"
   echo "If you know a spell to un-summon the drums,"
   echo "Nyarlathotep would probably weaken!"
   echo "Look up the *mv* command."
else
   echo "The drumming has stopped."
   echo "Now's your chance to attack!"
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./drummer
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

