#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
roll() {
    echo "Enter a number."
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    let "MONSTER=MONSTER+3"
    
    if [ ! -e drum ]; then
       let "MONSTER=MONSTER-2"
    fi
    
    echo "The monster rolled " $MONSTER
    echo "You rolled " $NUM

    if [[ -e wizard-dark && -e wizard-light ]]; then
	let "NUM=NUM+2"
	echo "+2 Arnnisen the Gray"
    fi

if [[ -e ../../.bless ]]; then
	let "NUM=NUM+2"
	echo "+2 POSIX wizard bonus!"
    fi
    resolve
}

gameover () {
    echo "You see the corpse of a slain adventurer on the floor of the dungeon." > corpse
    echo "You find the following items on the corpse:  " >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

flee () {
    echo "You turn to flee but find that you cannot."
    echo "You spend 1000 years as a mindless servant to the crawling chaos."
    echo "When you awaken, you may attempt to fight for your liberation."
    printf "\n"

}
resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
	echo "You dodge an attack, but you miss your mark as a result."
	echo "Roll again..."
	roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
       echo "A hit! A palpable hit!"
       echo "You have vanquished the elder god of chaos!"

       echo '#!/bin/sh
       if ! grep -Po hair <<< $I &> /dev/null; then
           echo "You have found a lock of the **hair** of a god!"
           echo "Add it to your inventory."
       else 
           echo "This treasure has already been taken."
       fi' > treasure
       chmod +x treasure
       echo '#!/bin/sh
       if ! grep -Po bracelet <<< $I &> /dev/null; then
           echo "You have found an enchanted *bracelet* of chaotic necromancy!"
           echo "Add it to your inventory." 
       else
           echo "This treasure has already been taken."
       fi' > platinum
    chmod +x platinum
       cat << EOF > end 
You have reached the end of the game. 
You know enough Bash now to use it for every day activities.
Practice makes perfect, so be sure to use it often.
For continued Bash tips, visit opensource.com often.
And eventually, we hope to see you contribute
your own dungeon rooms to Bash crawl!
EOF

    else
    	echo "Your sword swings harmlessly through the air."
    	echo "You take 10 points damage from your foe. Deduct this from your HP."
    	echo 'let "HP=HP-10"'
        let HP=HP-10
        export HP
        if [ "$HP" -le 0 ]; then
            echo "The elder god of chaos consumes your body and soul."
            echo
            echo "You have been slain."
            echo
            echo "GAME OVER!"
            gameover
            exit 1
        fi
	    printf "\n"
	    roll
    fi
}

echo "In the blink of an eye, Nyarlathotep is standing before you."
echo "From its hands emanate black necrotic rays, and your mind screams."
printf "\n"
echo "Are you armed? y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then

    if grep -Po "sword" <<< $I &> /dev/null; then
        roll
    else
        echo "Oh, no!  You have lost your blade!"
        echo "Nyarlathotep, the elder god of chaos, senses your weakness."
        echo
        flee
    fi
else
    flee
fi
printf "\n"


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./nyarlathotep
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

