#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
roll() {
    echo "输入数字。"
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    let "MONSTER=MONSTER+3"
    
    if [ ! -e drum ]; then
       let "MONSTER=MONSTER-2"
    fi
    
    echo "奈亚拉托提普的数字是 " $MONSTER
    echo "你的数字是 " $NUM

    if [[ -e wizard-dark && -e wizard-light ]]; then
	let "NUM=NUM+2"
	echo "+2 Arnnisen the Gray"
    fi

if [[ -e ../../.bless ]]; then
	let "NUM=NUM+2"
	echo "+2 POSIX 法师加成！"
    fi
    resolve
}

gameover () {
    echo "你在地牢地板上看到一具冒险者的尸体（corpse）。" > corpse
    echo "尸体周围散落着这些物品：" >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

flee () {
    echo "你想逃跑，但跑不了。"
    echo "你要为伏行之混沌当 1000 年的无思想的卒。"
    echo "醒来的时候再试着为自由而战吧。"
    printf "\n"

}
resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
	echo "你躲过了奈亚拉托提普的攻击，但也没能打中目标。"
	echo "再来一局……"
	roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
       echo "打中了！效果拔群！"
       echo "你击败了混沌之古神！"

       echo '#!/bin/bash
       if ! grep -Po hair <<< $I &> /dev/null; then
           echo "你发现了神的一绺 **头发** （hair）！"
           echo "把它装入物品栏吧。"
       else 
           echo "宝藏已经被取走了。"
       fi' > treasure
       chmod +x treasure
       echo '#!/bin/bash
       if ! grep -Po bracelet <<< $I &> /dev/null; then
           echo "你找到了一把混沌死灵法师的附魔 *手镯* （bracelet）！"
           echo "把它装入物品栏吧。"
       else
           echo "宝藏已经被取走了。"
       fi' > platinum
    chmod +x platinum
       cat << EOF > end 
看来您已经打到了游戏尽头。
您已足以在日常中使用 bash。
熟能生巧，您要保证经常用 bash。
若是想要更多 bash 技巧，请常看看 opensource.com 。
期待看到您向 bashcrawl 贡献自己设计的地牢房间！
EOF

    else
    	echo "你在空气中晃悠的打法造不成一点伤害。"
    	echo "敌人对你造成了 10 点伤害，要从 HP 中减掉。"
    	echo 'let "HP=HP-10"'
        let HP=HP-10
        export HP
        if [ "$HP" -le 0 ]; then
            echo "混沌之古神榨干了你的身体和灵魂。"
            echo
            echo "你被杀害了。"
            echo
            echo "游戏结束！"
            gameover
            exit 1
        fi
	    printf "\n"
	    roll
    fi
}

echo "一眨眼，奈亚拉托提普就已出现在你身后。"
echo "它的手发射着黑色的坏死射线，你的意识在尖叫。"
printf "\n"
echo "你有带武器吗？y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then

    if grep -Po "sword" <<< $I &> /dev/null; then
        roll
    else
        echo "哦不！你没有剑！"
        echo "奈亚拉托提普——混沌之古神，察觉到了你的弱点。"
        echo
        flee
    fi
else
    flee
fi
printf "\n"


















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./nyarlathotep
#
# 要是没看到文件名后的“*”，搞不好是因为你忘记用 ls -F 了。

