#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
if [ -e wizard-dark ]; then
   echo "The ancient wizard, Arnnisen the Gray,"
   echo "takes form before your very eyes. You"
   echo "have freed him, and now he fights by"
   echo "your side against the crawling chaos!"
else
   echo "You feel a presence."
   echo "It's probably just your imagination."
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./wizard-light
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

