#!/bin/bash
#
# 如果您在阅读这句话，您就已经跨越游戏本身的界限，
# 而正在阅读着驱动游戏运行的代码了。
#
#                              祝贺你！
#
# 学习 Linux 完全是为了满足好奇心，您可以阅读一下这段代码，
# 看看能不能搞清它的作用机理。
#
# 然而要是准备好继续游戏了，就要继续阅读卷轴（scroll）。如果在哪卡住了，
# 就去 Gitlab 上的页面发一条 Issue。我们乐于提供提示。
#
#
echo "你有水晶吗？"
printf "\n"
read RESP

no_crystal () {
   echo "你感知到玻璃片在寻找着什么。"
   echo "不管是啥，你还都没法确定。"
   echo "还是小心为好。"
}
if [ $RESP = "y" -o $RESP = "Y" ]; then
    if grep -Po crystal <<< $I &> /dev/null; then
        echo "你把水晶放在玻璃片间。"
        echo "你手中的剑突然变得非常凉。"
        echo "你感受到了 1000 场暴雪穿梭的力量。"
        touch .bless
    else
        no_crystal
    fi
else
    no_crystal
fi


















































































































































































































































































# 嗯，这样行不通。
# 别忘了，以“*”结尾的是程序。
#
# 试试这样：
#
# ./glass


